name: Lighthouse CI

on: [push]

jobs:
  lighthouseci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn && yarn global add @lhci/cli@0.3.x
      - run: yarn build
      - run: yarn lhci
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
